server:
  port: 11001
eureka:
  instance:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    # 访问路径可以显示IP
    prefer-ip-address: true
    # 自定义instance-id
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: order-service
  zipkin:
    base-url: http://www.limaila.com:9411/
  sleuth:
    sampler:
      probability: 1

# 配置product-service 使用随机方式的rule，默认是轮训的rule，线上最好使用默认的
product-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

# 全局配置feign超时时间，如果不配置fiegn的超时时间是10秒，连接时间是60秒，
# 但是由于feign默认的hystrix的超时时间是1秒，导致最终feign的超时时间为1秒 ，可以通过feign.hystrix.enable=false关闭hystrix
feign:
  client:
    config:
      default:
        # 设置超时连接时间为2秒 和 读时间为2秒
        connectTimeout: 2000
        readTimeout: 2000
  hystrix:
    # feign开启hystrix
    enabled: true


hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # hystrix 超时时间为1秒
            timeoutInMilliseconds: 5000
        timeout:
          # 开启hystrix超时机制
          enabled: true
