server:
  port: 10001
eureka:
  instance:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    # 访问路径可以显示IP
    prefer-ip-address: true
    # 自定义instance-id
    instance-id: ${spring.application.name}:${server.port}
spring:
  application:
    name: product-service
  zipkin:
    base-url: http://www.limaila.com:9411/
    sender:
      type: web
#    sender:
#      type: rabbit
  sleuth:
    sampler:
      probability: 1
#  rabbitmq:
#    addresses: www.limaila.cm
#    port: 5672
#    username: guest
#    password: guest


